buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"

locales:
  - en

# The site stream allows for specification of site entity whose data will be injected to all
# generation contexts under the `_site` property.
siteStream:
  id: site-stream
  entityId: blogStarter_site
  fields:
    - logo
    - blogStarter_headerLinks
    - blogStarter_footerLinks
# responseHeaders:
#   - pathPattern: .*
#     headerKey: joe-custom-header
#     headerValues:
#       - joe-custom-value

# Static redirects can establish redirects from individual source paths to individual destination paths.
staticRedirects:
  - from: /financial-professionals/fp-0913
    to: https://properly-oriented-ocelot.pgsdemo.com/financial-professionals/fp-0913
    status: 301
  # static rewrite
  - from: /ski-home
    to: https://commerce.skiware.us/unique-slug
    status: 200
# Dynamic redirects can establish redirect groups based on pattern matching.
dynamicRedirects:
  - from: /men/*
    to: https://commerce.skiware.us/men/:splat
    status: 302
  # static rewrite
  - from: /women/*
    to: https://commerce.skiware.us/women/:splat
    status: 200
# The sitemap configuration allows for customization or disabling of automated sitemap generation.
# sitemap:
#   excludeList:
#     - exclude1
#     - exclude2
#   disableSitemapGeneration: true
#   fileName: fancy-sitemap

# The authentication configuration allows for usage of a site-level or page-level authentication policy.
# authentication:
#   policyName: example-policy

# The serving configuration allows for specification of a reverse proxy domain.
# serving:
#   reverseProxyDomain: reverseproxy.com/path
